### PR TITLE
Enforce braces errywhere

### PR DESCRIPTION
**Pull request by ghost**
http://eslint.org/docs/rules/curly#all

Will merge with `7` (> 50% of 13 (engineering)) approvals/votes.

### CODE REVIEW

**Comment by roballsopp** [comment]
👎 so unclean

**Review by jwaldrip — CHANGES_REQUESTED** [review]
no

**Review by jpbarela — CHANGES_REQUESTED** [review]
no

**Comment by cprebble** [comment]
Approve. (And they're curly 'braces'.)

**Review by k7k0 — CHANGES_REQUESTED** [review]
I'm ok with both, but cooler if we allow brace-less single-line

**Review by aacotroneo — APPROVED** [review]
simply because having 2 ways to write the same thing is bad... I would even prefer a 'curly-never' rather than allowing both.

**Comment by cdriscol** [comment]
started to make this change and maybe i am somewhat opposed..

I prefer:
```
if (!showThreshold) threshold = 0;
else if (this.isFiveStar()) threshold = 1;
else threshold = this.getCriteriaMin();
```

over:
```
if (!showThreshold) {
  threshold = 0;
} else if (this.isFiveStar()) {
  threshold = 1;
} else {
  threshold = this.getCriteriaMin();
}
```

So I prefer the `multi` enforcement

**Comment by EIrwin** [comment]
Is there a `random` option? I like to be spontaneous

**Review by facupedrazzini — APPROVED** [review]

**Comment by styree** [comment]
Hesitant on this cause I really like my single line `if` statements. Maybe `multi` instead of `all`?

**Comment by ghost** [comment]
@styree Already multi currently, this would be more strict.

**Comment by cdriscol** [comment]
🍿

**Comment by EIrwin** [comment]
e20f9bb61abd2642cfda5ef4fdcdf0e0268d89b63419fefcb9f75ed889632a48

**Pull request closed without merging**
